const mongoose = require("mongoose");
const { Schema } = mongoose;

const Sesion = new Schema(
  {
    sip: String,
    monitor: { type: String, uppercase: true },
    numeroSerieMonitor: { type:String, uppercase: true },
    facultativo: { type: String, uppercase: true },
    fRegistro: { type: Date, default: Date.now() },
    horasSesion: String,
    dializador: { type: String, uppercase: true },
    accesoVascular: { type:String, uppercase: true },
    tipobano: { type:String, uppercase: true },
    basebano: { type:String, uppercase: true },
    bano: { type:String, uppercase: true },
    pesoseco: Number,
    ufmax: Number,
    ac: { type:String, uppercase: true },
    qd: Number,
    obsfacultativo: { type:String, uppercase: true },
    fecha: Date,
    Hora: String,
    peso_con: Number,
    peso_Desc: Number,
    uf: Number,
    tasa: Number,
    volsanguineo: Number,
    sintomas: [],
    lote: { type:String, uppercase: true },
    obspaciente: String,
    conTA: { type:String, uppercase: true },
    conFC: Number,
    conTEMP: Number,
    conQB: Number,
    conPV: Number,
    conPA: Number,
    unaHoraTA: { type:String, uppercase: true },
    unaHoraFC: Number,
    unaHoraTEMP: Number,
    unaHoraQB: Number,
    unaHoraPV: Number,
    unaHoraPA: Number,
    dosHoraTA: { type:String, uppercase: true },
    dosHoraFC: Number,
    dosHoraTEMP: Number,
    dosHoraQB: Number,
    dosHoraPV: Number,
    dosHoraPA: Number,
    descHoraTA: { type:String, uppercase: true },
    descHoraFC: Number,
    descHoraTEMP: Number,
    descHoraQB: Number,
    descHoraPV: Number,
    descHoraPA: Number,
    estado: { type: String, enum: ["R", "F", "C"], default:"R" }, // Registrado, Finalizada o en Confirmada
  },
  { versionKey: false }
);

module.exports = mongoose.model("Sesion", Sesion);
